"""Import an asset described by an AssetDescriptor into Houdini.

Consumes the shared dcc_mcp_core.asset_import contract and creates a geo
container with a File SOP to import the asset file. Returns a typed
ImportToSceneResult with imported node paths and any non-fatal warnings.
"""

from __future__ import annotations

import os
import re
from typing import Any, Mapping, Optional

from dcc_mcp_core.asset_import import (
    AssetDescriptor,
    AssetFileVariant,
    ImportToSceneResult,
    ImportWarning,
    ImportWarningCode,
    MaterialMode,
    PlacementHint,
)
from dcc_mcp_core.skill import skill_entry, skill_error, skill_exception, skill_success


def _safe_node_name(asset_id: str) -> str:
    """Convert an asset_id into a safe Houdini node name."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", asset_id)


def _pick_variant(descriptor: AssetDescriptor) -> AssetFileVariant | None:
    """Pick the best file variant from the descriptor."""
    for variant in descriptor.variants:
        if variant.preferred:
            return variant
    if descriptor.variants:
        return descriptor.variants[0]
    return None


def _apply_placement(
    hou: Any,
    obj_node: Any,
    placement: PlacementHint,
) -> list[ImportWarning]:
    """Apply placement hints to the imported geo container.

    Returns any warnings encountered.
    """
    warnings: list[ImportWarning] = []

    if placement.translate:
        obj_node.setParms({
            "tx": placement.translate[0] if len(placement.translate) > 0 else 0.0,
            "ty": placement.translate[1] if len(placement.translate) > 1 else 0.0,
            "tz": placement.translate[2] if len(placement.translate) > 2 else 0.0,
        })

    if placement.rotate:
        obj_node.setParms({
            "rx": placement.rotate[0] if len(placement.rotate) > 0 else 0.0,
            "ry": placement.rotate[1] if len(placement.rotate) > 1 else 0.0,
            "rz": placement.rotate[2] if len(placement.rotate) > 2 else 0.0,
        })

    if placement.scale:
        obj_node.setParms({
            "sx": placement.scale[0] if len(placement.scale) > 0 else 1.0,
            "sy": placement.scale[1] if len(placement.scale) > 1 else 1.0,
            "sz": placement.scale[2] if len(placement.scale) > 2 else 1.0,
        })

    if placement.parent_name:
        parent = hou.node(placement.parent_name)
        if parent:
            obj_node.setInput(0, parent)
        else:
            warnings.append(
                ImportWarning(
                    code=ImportWarningCode.UNKNOWN,
                    message=f"Parent node '{placement.parent_name}' not found",
                )
            )

    return warnings


def _import_file_to_houdini(
    hou: Any,
    filepath: str,
    node_name: str,
    parent_path: str = "/obj",
) -> tuple[list[str], list[ImportWarning]]:
    """Import a file into a Houdini geo container via a File SOP.

    Returns (imported_node_paths, warnings).
    """
    warnings: list[ImportWarning] = []
    expanded = os.path.expandvars(os.path.expanduser(filepath))

    if not os.path.exists(expanded):
        raise FileNotFoundError(f"Asset file not found: {expanded}")

    # Get or create the parent network
    parent = hou.node(parent_path)
    if parent is None:
        raise RuntimeError(f"Parent network not found: {parent_path}")

    # Create a geo container for the asset
    container = parent.createNode("geo", node_name=node_name)
    container_path = container.path()

    # Create a File SOP inside the container to read the asset file
    file_sop = container.createNode("file")
    file_sop.parm("file").set(expanded)

    # Cook to load geometry
    try:
        file_sop.cook(force=True)
    except Exception as exc:
        warnings.append(
            ImportWarning(
                code=ImportWarningCode.UNKNOWN,
                message=f"Cook warning: {exc}",
            )
        )

    # Collect imported node names
    imported_nodes = [container_path]
    # List children of the geo container (generated by File SOP processing)
    for child in container.children():
        imported_nodes.append(child.path())

    return imported_nodes, warnings


def import_to_scene(
    descriptor: Mapping[str, Any],
    material_mode: str = MaterialMode.AS_AUTHORED,
    placement: Optional[Mapping[str, Any]] = None,
    target_collection: Optional[str] = None,
    skip_existing: bool = False,
) -> dict:
    """Import an asset into Houdini.

    Args:
        descriptor: AssetDescriptor dict (from dcc_mcp_core.asset_import).
        material_mode: Material handling mode (as_authored, default_gray, skip).
        placement: Optional placement hint dict.
        target_collection: Optional parent network path (default /obj).
        skip_existing: Skip if asset_id already present in the scene.

    Returns:
        ActionResultModel dict with ImportToSceneResult in context.
    """
    try:
        import hou  # noqa: PLC0415
    except ImportError:
        return skill_error(
            "Houdini not available",
            "hou could not be imported — this skill must run inside Houdini",
        )

    try:
        desc = AssetDescriptor.from_dict(descriptor)
        desc.validate()
    except Exception as exc:
        return skill_error(
            f"Invalid AssetDescriptor: {exc}",
            "descriptor failed validation — check asset_id and variants",
        )

    node_name = _safe_node_name(desc.asset_id)
    parent_path = target_collection or "/obj"

    # Skip existing check
    if skip_existing:
        full_path = f"{parent_path}/{node_name}"
        if hou.node(full_path) is not None:
            return skill_success(
                f"Asset '{desc.asset_id}' already present in scene (skipped)",
                asset_id=desc.asset_id,
                skipped=True,
                prompt="Asset is already in the scene. No import needed.",
            )

    # Pick variant
    variant = _pick_variant(desc)
    if variant is None:
        return skill_error(
            f"No file variant available for '{desc.asset_id}'",
            "descriptor.variants is empty",
        )

    filepath = variant.local_path

    # Build placement hint
    placement_hint = None
    if placement:
        placement_hint = PlacementHint.from_dict(placement)

    try:
        imported_nodes, warnings = _import_file_to_houdini(hou, filepath, node_name, parent_path)
    except Exception as exc:
        return skill_exception(exc, message=f"Failed to import {filepath}")

    # Apply unit conversion: Houdini uses 1 unit = 1 meter natively
    if desc.meters_per_unit != 1.0:
        scale_factor = desc.meters_per_unit
        container = hou.node(imported_nodes[0]) if imported_nodes else None
        if container:
            current_scale = container.parm("scale")
            if current_scale:
                current_scale.set(scale_factor)

    # Apply placement
    if placement_hint:
        container = hou.node(imported_nodes[0]) if imported_nodes else None
        if container:
            placement_warnings = _apply_placement(hou, container, placement_hint)
            warnings.extend(placement_warnings)

    # Tag the container with asset_id for skip_existing support
    container = hou.node(imported_nodes[0]) if imported_nodes else None
    if container:
        container.setComment(f"dcc_mcp_asset_id: {desc.asset_id}")
        container.setUserData("dcc_mcp_asset_id", desc.asset_id)

    result = ImportToSceneResult(
        success=True,
        imported_nodes=imported_nodes,
        warnings=warnings,
    )

    return skill_success(
        f"Imported '{desc.asset_id}' into Houdini ({len(imported_nodes)} node(s))",
        **result.to_dict(),
        prompt=f"Imported {len(imported_nodes)} node(s). Use get_scene_info or list_obj_nodes to inspect.",
    )


@skill_entry
def main(**kwargs) -> dict:
    """Entry point; delegates to :func:`import_to_scene`."""
    return import_to_scene(**kwargs)


if __name__ == "__main__":
    from dcc_mcp_core.skill import run_main

    run_main(main)
