"""Import an asset described by an AssetDescriptor into Houdini.

Consumes the shared dcc_mcp_core.asset_import contract and creates a geo
container with a File SOP to import the asset file. Returns a typed
ImportToSceneResult with imported node paths and any non-fatal warnings.
"""

from __future__ import annotations

import os
import re
from typing import Any, Mapping, Optional

from _asset_material_import import build_materials, decode_materials_report, detect_material_format
from dcc_mcp_core.asset_import import (
    AssetDescriptor,
    AssetFileVariant,
    ImportToSceneResult,
    ImportWarning,
    ImportWarningCode,
    MaterialMode,
    PlacementHint,
)
from dcc_mcp_core.skill import skill_entry, skill_error, skill_exception, skill_success

VALID_MATERIAL_MODES = (MaterialMode.AS_AUTHORED, MaterialMode.DEFAULT_GRAY, MaterialMode.SKIP)


def _safe_node_name(asset_id: str) -> str:
    """Convert an asset_id into a safe Houdini node name."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", asset_id)


def _pick_variant(descriptor: AssetDescriptor) -> AssetFileVariant | None:
    """Pick the best file variant from the descriptor."""
    for variant in descriptor.variants:
        if variant.preferred:
            return variant
    if descriptor.variants:
        return descriptor.variants[0]
    return None


def _apply_placement(
    hou: Any,
    obj_node: Any,
    placement: PlacementHint,
) -> list[ImportWarning]:
    """Apply placement hints to the imported geo container.

    Returns any warnings encountered.
    """
    warnings: list[ImportWarning] = []

    if placement.translate:
        obj_node.setParms(
            {
                "tx": placement.translate[0] if len(placement.translate) > 0 else 0.0,
                "ty": placement.translate[1] if len(placement.translate) > 1 else 0.0,
                "tz": placement.translate[2] if len(placement.translate) > 2 else 0.0,
            }
        )

    if placement.rotate:
        obj_node.setParms(
            {
                "rx": placement.rotate[0] if len(placement.rotate) > 0 else 0.0,
                "ry": placement.rotate[1] if len(placement.rotate) > 1 else 0.0,
                "rz": placement.rotate[2] if len(placement.rotate) > 2 else 0.0,
            }
        )

    if placement.scale:
        obj_node.setParms(
            {
                "sx": placement.scale[0] if len(placement.scale) > 0 else 1.0,
                "sy": placement.scale[1] if len(placement.scale) > 1 else 1.0,
                "sz": placement.scale[2] if len(placement.scale) > 2 else 1.0,
            }
        )

    if placement.parent_name:
        parent = hou.node(placement.parent_name)
        if parent:
            obj_node.setInput(0, parent)
        else:
            warnings.append(
                ImportWarning(
                    code=ImportWarningCode.UNKNOWN,
                    message=f"Parent node '{placement.parent_name}' not found",
                )
            )

    return warnings


def _import_file_to_houdini(
    hou: Any,
    filepath: str,
    node_name: str,
    parent_path: str = "/obj",
) -> tuple[list[str], list[ImportWarning]]:
    """Import a file into a Houdini geo container via a File SOP.

    *filepath* must already be user- and variable-expanded (see
    :func:`_expand_path`) so the geometry import and the material decode agree
    on one single path.

    Returns (imported_node_paths, warnings).
    """
    warnings: list[ImportWarning] = []
    expanded = filepath

    if not os.path.exists(expanded):
        raise FileNotFoundError(f"Asset file not found: {expanded}")

    # Get or create the parent network
    parent = hou.node(parent_path)
    if parent is None:
        raise RuntimeError(f"Parent network not found: {parent_path}")

    # Create a geo container for the asset
    container = parent.createNode("geo", node_name=node_name)
    container_path = container.path()

    # Create a File SOP inside the container to read the asset file
    file_sop = container.createNode("file")
    file_sop.parm("file").set(expanded)

    # Cook to load geometry
    try:
        file_sop.cook(force=True)
    except Exception as exc:
        warnings.append(
            ImportWarning(
                code=ImportWarningCode.UNKNOWN,
                message=f"Cook warning: {exc}",
            )
        )

    # Collect imported node names
    imported_nodes = [container_path]
    # List children of the geo container (generated by File SOP processing)
    for child in container.children():
        imported_nodes.append(child.path())

    return imported_nodes, warnings


def _expand_path(filepath: str) -> str:
    """Expand ``~`` and environment variables in *filepath* exactly once."""
    return os.path.expandvars(os.path.expanduser(filepath))


def _apply_material_mode(
    hou: Any,
    container: Any,
    material_mode: str,
    filepath: str,
    variant_format: Optional[str],
    name_prefix: str,
) -> dict:
    """Honour *material_mode* for the freshly imported *container*.

    The File-SOP import path carries geometry only, so ``as_authored`` has to be
    reconstructed from the carrier itself.  Whatever happens, the returned
    report tells the caller exactly how many materials landed, so the import
    can warn instead of silently dropping the look of the asset.
    """
    report: dict = {
        "material_mode": material_mode,
        "materials_detected": 0,
        "materials_imported": 0,
        "material_paths": [],
        "material_assignments": [],
        "unapplied_parameters": [],
        "unapplied_required": [],
        "status": "skipped",
        "warnings": [],
    }

    if container is None:
        return report

    if material_mode == MaterialMode.SKIP:
        return report

    if material_mode == MaterialMode.DEFAULT_GRAY:
        built = build_materials(
            hou,
            [
                {
                    "name": "default_gray",
                    "base_color": [0.5, 0.5, 0.5],
                    "metallic": 0.0,
                    "roughness": 0.5,
                    "emissive": None,
                    "opacity": 1.0,
                }
            ],
            container,
            name_prefix=name_prefix,
        )
        report["status"] = "default_gray" if built["created"] else "failed"
        report["materials_imported"] = len(built["created"])
        report["material_paths"] = list(built["created"])
        report["material_assignments"] = list(built["assigned"])
        if not built["created"]:
            report["warnings"].append(
                ImportWarning(
                    code=ImportWarningCode.MATERIAL_FALLBACK,
                    message=(
                        "material_mode='default_gray' was requested but no material could be created; "
                        "the imported geometry has no material assignment"
                    ),
                )
            )
        return report

    material_format = detect_material_format(filepath, variant_format)
    specs, status, decode_detail = decode_materials_report(filepath, material_format)
    report["status"] = status

    if status == "decoded" and specs:
        report["materials_detected"] = len(specs)
        built = build_materials(hou, specs, container, name_prefix=name_prefix)
        report["materials_imported"] = len(built["created"])
        report["material_paths"] = list(built["created"])
        report["material_assignments"] = list(built["assigned"])
        report["unapplied_parameters"] = list(built["unapplied"])
        report["unapplied_required"] = list(built["unapplied_required"])
        if built["created"]:
            report["status"] = "as_authored"

    detail = "file={0}; format={1}".format(filepath, material_format or "unknown")

    def _fallback(reason: str) -> None:
        report["warnings"].append(
            ImportWarning(
                code=ImportWarningCode.MATERIAL_FALLBACK,
                message=(
                    "material_mode='as_authored' was requested but the authored materials were not imported: " + reason
                ),
                detail=detail,
            )
        )

    if report["materials_imported"] == 0:
        reason = {
            "unsupported_format": "this adapter has no material path for '{0}' carriers".format(
                material_format or "unknown"
            ),
            "decode_failed": "the carrier could not be decoded for materials",
            "carrier_unreadable": "the carrier declares materials that could not be read",
            "decoded": "no material node could be created in the scene",
        }.get(status)
        if reason is not None and decode_detail:
            reason = "{0} ({1})".format(reason, decode_detail)
        # ``no_materials`` is the only quiet outcome: the carrier was read and
        # genuinely carries no materials, so nothing was lost.
        if reason is not None:
            _fallback(reason)
    elif report["unapplied_required"]:
        # Materials exist but the shader did not expose the parms that carry
        # the base look, so the imported material is not the authored one.
        _fallback("the shader does not expose {0}".format(", ".join(report["unapplied_required"])))
    return report


def import_to_scene(
    descriptor: Mapping[str, Any],
    material_mode: str = MaterialMode.AS_AUTHORED,
    placement: Optional[Mapping[str, Any]] = None,
    target_collection: Optional[str] = None,
    skip_existing: bool = False,
) -> dict:
    """Import an asset into Houdini.

    Args:
        descriptor: AssetDescriptor dict (from dcc_mcp_core.asset_import).
        material_mode: Material handling mode (as_authored, default_gray, skip).
        placement: Optional placement hint dict.
        target_collection: Optional parent network path (default /obj).
        skip_existing: Skip if asset_id already present in the scene.

    Returns:
        ActionResultModel dict with ImportToSceneResult in context.  Material
        fidelity is reported through ``context.extra`` (``material_mode``,
        ``materials_detected``, ``materials_imported``, ``material_paths``,
        ``material_assignments``) and, when ``as_authored`` could not be
        honoured, through a ``material_fallback`` warning.
    """
    try:
        import hou  # noqa: PLC0415
    except ImportError:
        return skill_error(
            "Houdini not available",
            "hou could not be imported — this skill must run inside Houdini",
        )

    mode = material_mode or MaterialMode.AS_AUTHORED
    if mode not in VALID_MATERIAL_MODES:
        return skill_error(
            "Unsupported material_mode '{0}'".format(mode),
            "material_mode must be one of: {0}".format(", ".join(VALID_MATERIAL_MODES)),
            material_mode=material_mode,
            supported_modes=list(VALID_MATERIAL_MODES),
        )

    try:
        desc = AssetDescriptor.from_dict(descriptor)
        desc.validate()
    except Exception as exc:
        return skill_error(
            f"Invalid AssetDescriptor: {exc}",
            "descriptor failed validation — check asset_id and variants",
        )

    node_name = _safe_node_name(desc.asset_id)
    parent_path = target_collection or "/obj"

    # Skip existing check
    if skip_existing:
        full_path = f"{parent_path}/{node_name}"
        if hou.node(full_path) is not None:
            return skill_success(
                f"Asset '{desc.asset_id}' already present in scene (skipped)",
                asset_id=desc.asset_id,
                skipped=True,
                prompt="Asset is already in the scene. No import needed.",
            )

    # Pick variant
    variant = _pick_variant(desc)
    if variant is None:
        return skill_error(
            f"No file variant available for '{desc.asset_id}'",
            "descriptor.variants is empty",
        )

    # Expand exactly once: the geometry import and the material decode must
    # look at the same file (`$ASSETS/x.glb` used to reach the File SOP but
    # not the material decoder).
    filepath = _expand_path(variant.local_path)

    # Build placement hint
    placement_hint = None
    if placement:
        placement_hint = PlacementHint.from_dict(placement)

    try:
        imported_nodes, warnings = _import_file_to_houdini(hou, filepath, node_name, parent_path)
    except Exception as exc:
        return skill_exception(exc, message=f"Failed to import {filepath}")

    # Apply unit conversion: Houdini uses 1 unit = 1 meter natively
    if desc.meters_per_unit != 1.0:
        scale_factor = desc.meters_per_unit
        container = hou.node(imported_nodes[0]) if imported_nodes else None
        if container:
            current_scale = container.parm("scale")
            if current_scale:
                current_scale.set(scale_factor)

    # Apply placement
    if placement_hint:
        container = hou.node(imported_nodes[0]) if imported_nodes else None
        if container:
            placement_warnings = _apply_placement(hou, container, placement_hint)
            warnings.extend(placement_warnings)

    # Tag the container with asset_id for skip_existing support
    container = hou.node(imported_nodes[0]) if imported_nodes else None
    if container:
        container.setComment(f"dcc_mcp_asset_id: {desc.asset_id}")
        container.setUserData("dcc_mcp_asset_id", desc.asset_id)

    # Materials: the File SOP carries geometry only, so the requested mode has
    # to be honoured explicitly (and reported, never dropped in silence).
    material_report = _apply_material_mode(
        hou,
        container,
        mode,
        filepath,
        getattr(variant, "format", None),
        _safe_node_name(desc.asset_id) + "_",
    )
    warnings.extend(material_report.pop("warnings"))

    scene_nodes = list(imported_nodes) + list(material_report["material_paths"])
    result = ImportToSceneResult(
        success=True,
        imported_nodes=scene_nodes,
        warnings=warnings,
        extra=material_report,
    )

    imported_count = material_report["materials_imported"]
    material_note = "{0} material(s)".format(imported_count)
    if imported_count == 0 and mode != MaterialMode.SKIP:
        material_note += " (material_mode='{0}' was not honoured)".format(mode)

    return skill_success(
        f"Imported '{desc.asset_id}' into Houdini ({len(imported_nodes)} node(s), {material_note})",
        **result.to_dict(),
        prompt=(
            f"Imported {len(imported_nodes)} geometry node(s) into {parent_path}. "
            f"material_mode='{mode}' -> {material_report['status']}, "
            f"{imported_count} material(s) created at {material_report['material_paths'] or 'n/a'}."
            + (
                " WARNING: materials were dropped — see context.warnings (code=material_fallback)."
                if any(w.code == ImportWarningCode.MATERIAL_FALLBACK for w in warnings)
                else ""
            )
        ),
    )


@skill_entry
def main(**kwargs) -> dict:
    """Entry point; delegates to :func:`import_to_scene`."""
    return import_to_scene(**kwargs)


if __name__ == "__main__":
    from dcc_mcp_core.skill import run_main

    run_main(main)
